server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # jws-algorithms: HS256
          jws-algorithms: RS512
          # jws-algorithms: RS256
          # public-key-location: classpath:certs/publicKey.txt
          issuer-uri: